### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by agerlach** [JuliaReach/Flowstar.jl#28]
@JuliaRegistrator register()

**Comment by agerlach** [comment]
@mforets I'm not quite sure whats going on here. I added the Register bot and tried this and the same as a comment on the last commit. This is my first rodeo registering. Any help is appreciated.

**Comment by schillic** [comment]
The app was not activated. I just approved it. You can try again :)

**Comment by agerlach** [comment]
@JuliaRegistrator register()

**Comment by agerlach** [comment]
@schillic Any preference on the version note above?

**Comment by schillic** [comment]
I think it is fine to start with v0.2.4. I understand the intention behind the note, but it does not always apply. I would normally not downgrade the version, so the only reasonable change would be to go for v1.0.0. But that somewhat indicates a stable version. If you feel that the package has reached this stage, I would go for it. If you still consider it in a preliminary stage, I would keep it as is. But really up to you.

**Comment by agerlach** [comment]
I will leave it
